### ISSUE TITLE
setAutoCommit and transactions

### ISSUE THREAD

**Issue by Narigo** [vert-x3/vertx-mysql-postgresql-service#2]
There are a couple of cases that we need to look at, when providing and simulating the `setAutoCommit()` from JDBC with this driver. In PostgreSQL you don't really set auto commit on and off, you just begin and commit or rollback a transaction.

From what I've learned from JDBC documentation is the following:

If `setAutoCommit` changes from `true` (default) to `false`, it will start a transaction.
If `setAutoCommit` changes from `false` to `true`, it will commit a transaction.
If you commit or rollback and have auto commit set to false, it will commit or rollback and start a new transaction immediately afterwards.
If you call setAutoCommit() and it doesn't change from the current setting, it will do nothing (= call the success callback immediately)
If you commit or rollback when auto commit is set to true, it will (most probably) fail due to a database error (you cannot commit/rollback when no transaction is running).

From my point of view, this `setAutoCommit(boolean)` adds complexity for the user, which could be mitigated if we would just provide a method called `startTransaction`. The user can call it to begin a transaction. With `setAutoCommit()` we handle the stuff behind the users back: On a commit or rollback, we immediately start a new connection by issuing another command to the database.

I'm also not sure yet, what to do when the user closes a connection. As it should be put back into the connection pool, I believe it should automatically call `setAutoCommit(false)` and then give the connection back to the pool. I'm not sure how to solve the problem if someone commits and then closes the connection: This would call the database twice with two commands: 1. begin new transaction and 2. commit the (empty) transaction.

WDYT?

**Comment by Narigo** [comment]
Updated the issue as I came on the create button while typing... if you got an email with a strange issue before, please have a look at it now on GitHub issues, thanks!

**Comment by purplefox** [comment]
I prefer setAutoCommit, most java users will be used to it already and the semantics are pretty simple. 

When a connection is closed autocommit should be set back to true which is the default value for a connection

**Comment by purplefox** [comment]
>> This would call the database twice with two commands: 1. begin new transaction and 2. commit the (empty) transaction.

This is unnecessary, you don't start a new transaction until the first transactional operation after the last transaction.

**Comment by Narigo** [comment]
Updated #1 with setAutoCommit. I also included a Java test that seems to throw an exception - would be great if you could take a look, most probably I'm just doing something wrong with this `onSuccess()` helper @purplefox 

Thanks!
